version: '3'

services:
  mysql:
    image: mysql:8
    ports:
     - "3306:3306"
    volumes:
      - mysql:/data/mysql
    restart: always
    environment:
      MYSQL_SERVER: 'localhost'
      MYSQL_DATABASE: 'locadora_IntegrationTests'
      MYSQL_ROOT_PASSWORD: 'Root@2022'
      MYSQL_PASSWORD: 'Root@2022'

volumes:
  mysql: